import type { SquareItem } from "./types";
import { PALETTES } from "./recipes";

/** 广场 mock 数据：之后替换为服务端已发布 Effect 列表 */
export const SQUARE_ITEMS: SquareItem[] = [
  {
    id: "sq-glass",
    name: "玻璃碎片",
    prompt: "玻璃碎裂成六瓣，弹幕沿碎片边缘流动",
    recipe: { symmetry: 6, rotationSpeed: 0.15, motion: "burst", palette: PALETTES.glass, shardScale: 1.1, trail: 0.55, density: 1 },
    author: "碎镜师傅",
    authorAvatarHue: "#00a1d6",
    likes: 1204,
    uses: 386,
    remixes: 57,
    tags: ["对称", "碎裂", "冰晶"],
    createdAt: Date.now() - 86400e3 * 12,
  },
  {
    id: "sq-mandala",
    name: "繁花曼陀罗",
    prompt: "弹幕像花瓣一样绽放成八重曼陀罗，缓慢旋转",
    recipe: { symmetry: 8, rotationSpeed: 0.1, motion: "spiral", palette: PALETTES.sakura, shardScale: 1, trail: 0.72, density: 1 },
    author: "花见小路",
    authorAvatarHue: "#fb7299",
    likes: 986,
    uses: 294,
    remixes: 41,
    tags: ["曼陀罗", "樱花", "旋转"],
    createdAt: Date.now() - 86400e3 * 9,
  },
  {
    id: "sq-galaxy",
    name: "星河轨道",
    prompt: "弹幕化作星辰沿银河轨道环绕，带长拖影",
    recipe: { symmetry: 5, rotationSpeed: 0.2, motion: "orbit", palette: PALETTES.neon, shardScale: 0.9, trail: 0.82, density: 0.9 },
    author: "轨道清洁工",
    authorAvatarHue: "#8b7cf6",
    likes: 854,
    uses: 251,
    remixes: 33,
    tags: ["星空", "轨道", "拖影"],
    createdAt: Date.now() - 86400e3 * 7,
  },
  {
    id: "sq-cyber",
    name: "赛博霓虹",
    prompt: "赛博朋克霓虹灯牌风格，弹幕高速穿行",
    recipe: { symmetry: 4, rotationSpeed: 0.26, motion: "flow", palette: PALETTES.cyber, shardScale: 1, trail: 0.75, density: 1.4 },
    author: "夜之城居民",
    authorAvatarHue: "#00f0ff",
    likes: 763,
    uses: 208,
    remixes: 26,
    tags: ["赛博", "霓虹", "高速"],
    createdAt: Date.now() - 86400e3 * 5,
  },
  {
    id: "sq-ember",
    name: "余烬飞旋",
    prompt: "壁炉余烬般的暖色弹幕，缓缓螺旋上升",
    recipe: { symmetry: 6, rotationSpeed: -0.14, motion: "spiral", palette: PALETTES.ember, shardScale: 0.95, trail: 0.65, density: 0.8 },
    author: "烤火观众",
    authorAvatarHue: "#ff9f29",
    likes: 512,
    uses: 143,
    remixes: 18,
    tags: ["暖色", "螺旋", "治愈"],
    createdAt: Date.now() - 86400e3 * 4,
  },
  {
    id: "sq-mono",
    name: "白夜极简",
    prompt: "只要纯白弹幕，三重对称，干净克制",
    recipe: { symmetry: 3, rotationSpeed: 0.06, motion: "orbit", palette: PALETTES.mono, shardScale: 0.85, trail: 0.4, density: 0.6 },
    author: "少即是多",
    authorAvatarHue: "#9aa3b2",
    likes: 431,
    uses: 122,
    remixes: 12,
    tags: ["极简", "纯白", "克制"],
    createdAt: Date.now() - 86400e3 * 3,
  },
  {
    id: "sq-sakura-storm",
    name: "樱吹雪",
    prompt: "樱花风暴，大量粉色弹幕随漩涡飞舞",
    recipe: { symmetry: 10, rotationSpeed: 0.3, motion: "spiral", palette: PALETTES.sakura, shardScale: 0.8, trail: 0.6, density: 1.8 },
    author: "花见小路",
    authorAvatarHue: "#fb7299",
    likes: 689,
    uses: 197,
    remixes: 29,
    tags: ["樱花", "高密度", "漩涡"],
    createdAt: Date.now() - 86400e3 * 2,
  },
  {
    id: "sq-prism",
    name: "棱镜折射",
    prompt: "弹幕穿过棱镜散成彩虹色，十二重对称",
    recipe: { symmetry: 12, rotationSpeed: 0.12, motion: "burst", palette: PALETTES.neon, shardScale: 0.75, trail: 0.5, density: 1.1 },
    author: "光学爱好者",
    authorAvatarHue: "#7ee0a3",
    likes: 377,
    uses: 96,
    remixes: 9,
    tags: ["棱镜", "彩虹", "对称"],
    createdAt: Date.now() - 86400e3 * 1,
  },
];

export function getSquareItem(id: string): SquareItem | undefined {
  return SQUARE_ITEMS.find((i) => i.id === id);
}
